---

- name: "[OCP4-INSTALL] Create Azure Openshift Cluster in Private/Disconnected Mode"
  hosts: localhost
  gather_facts: yes
  vars:
    vars_files_list:
      - vault/azure.yml
      - vars/vars-private.yml
      - vars/vars-firewall.yml # Only used in egress=firewall
      - vars/vars-nat-gateway.yml # Only used in egress=natgateway
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ azure_subscription_id }}"
    AZURE_TENANT: "{{ azure_tenant }}"
    AZURE_CLIENT_ID: "{{ azure_client_id }}"
    AZURE_SECRET: "{{ azure_secret }}"
  tasks:
    - name: Include vars_files
      include_vars: "{{ item }}"
      when: item is file
      loop: "{{ vars_files_list }}"
    - name: Provision Azure Infra and Deploy Bastion
      include_role:
        name: ocp4-cloud-ipi
      vars:
        action: provision-infra

- name: "[OCP4-INSTALL] Create Azure Openshift Cluster in Private/Disconnected mode"
  hosts: inv
  become: true
  vars:
    vars_files_list:
      - vault/azure.yml
      - vars/vars-private.yml
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ azure_subscription_id }}"
    AZURE_TENANT: "{{ azure_tenant }}"
    AZURE_CLIENT_ID: "{{ azure_client_id }}"
    AZURE_SECRET: "{{ azure_secret }}"
  tasks:
    - name: Include vars_files
      include_vars: "{{ item }}"
      when: item is file
      loop: "{{ vars_files_list }}"

    - name: Install SW and Configure Registry into the Bastion
      include_role:
        name: ocp4-cloud-ipi
      vars:
        action: prepare-bastion

    - name: Install cluster
      include_role:
        name: ocp4-cloud-ipi
      vars:
        action: install
